# Generated by Django 4.1.1 on 2024-11-21 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_profile_room_status_room'),
        ('base', '0005_remove_chatroom_name_alter_message_sender'),
    ]

    operations = [
    ]
