# Generated by Django 5.1.3 on 2024-11-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_remove_userprofile_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="interested_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="interested_rooms",
                through="base.Room_interested_users",
                to="base.profile",
            ),
        ),
    ]
