# Generated by Django 5.1.3 on 2024-11-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_alter_message_sender"),
        ("base", "0012_alter_room_interested_users"),
    ]

    operations = []
