# Generated by Django 5.1.3 on 2024-11-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_merge_20241124_1252"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="room_status",
            field=models.CharField(
                choices=[
                    ("offering", "Offering"),
                    ("available", "Available"),
                    ("occupied", "Occupied"),
                ],
                default="available",
                max_length=20,
            ),
        ),
    ]
