# Generated by Django 5.1.3 on 2024-11-24 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_userprofile_name_userprofile_room_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="room_status",
        ),
    ]
